var item={
    "list":[
          {
            "qtype":1,
            "img":"item/1.jpg",
            "option":["朝三暮四","日锻月炼","日高三丈","日积月累"],
            "right":"朝三暮四"
          },
          {
            "qtype":1,
            "img":"item/2.jpg",
            "option":["眉目传情","低眉顺眼","喜上眉梢","眉来眼去"],
            "right":"喜上眉梢"
          },
          {
            "qtype":1,
            "img":"item/3.jpg",
            "option":["插翅难飞","小心翼翼","比翼双飞","小心谨慎"],
            "right":"小心翼翼"
          },
          {
            "qtype":1,
            "img":"item/4.jpg",
            "option":["羊入虎口","扬长而去","狐假虎威","分道扬镳"],
            "right":"羊入虎口"
          },
          {
            "qtype":1,
            "img":"item/5.jpg",
            "option":["目中无人","不见泰山","一叶障目","穷根寻叶"],
            "right":"一叶障目"
          },
          {
            "qtype":1,
            "img":"item/6.jpg",
            "option":["纸上谈兵","鱼目混珠","得鱼忘筌","跃然纸上"],
            "right":"跃然纸上"
          },
          {
            "qtype":1,
            "img":"item/7.jpg",
            "option":["长短不一","粗中有细","错综复杂","细致入微"],
            "right":"粗中有细"
          },
          {
            "qtype":1,
            "img":"item/8.jpg",
            "option":["歪门邪道","背道而驰","旁门左道","道德败坏"],
            "right":"旁门左道"
          },
          {
            "qtype":1,
            "img":"item/9.jpg",
            "option":["衣食父母","衣食无忧","举案齐眉","相敬如宾"],
            "right":"衣食父母"
          },
          {
            "qtype":1,
            "img":"item/10.jpg",
            "option":["立竿见影","历历在目","日高三丈","日上三竿"],
            "right":"日上三竿"
          },
          {
            "qtype":2,
            "img":"item/11.jpg",
            "option":["水","滴","石","穿"]
          },
          {
            "qtype":2,
            "img":"item/12.jpg",
            "option":["纸","上","谈","兵"]
          },
          {
            "qtype":2,
            "img":"item/13.jpg",
            "option":["以","偏","概","全"]
          },
          {
            "qtype":2,
            "img":"item/14.jpg",
            "option":["逆","来","顺","受"]
          },
          {
            "qtype":2,
            "img":"item/15.jpg",
            "option":["瓜","熟","蒂","落"]
          },
          {
            "qtype":2,
            "img":"item/16.jpg",
            "option":["势","如","破","竹"]
          },
          {
            "qtype":2,
            "img":"item/17.jpg",
            "option":["支","离","破","碎"]
          },
          {
            "qtype":2,
            "img":"item/18.jpg",
            "option":["雪","中","送","炭"]
          },
          {
            "qtype":2,
            "img":"item/19.jpg",
            "option":["心","直","口","快"]
          },
          {
            "qtype":2,
            "img":"item/20.jpg",
            "option":["史","无","前","例"]
          },
          {
            "qtype":2,
            "img":"item/21.jpg",
            "option":["哭","笑","不","得"]
          },
          {
            "qtype":2,
            "img":"item/22.jpg",
            "option":["一","衣","带","水"]
          },
          {
            "qtype":2,
            "img":"item/23.jpg",
            "option":["绕","梁","三","日"]
          },
          {
            "qtype":2,
            "img":"item/24.jpg",
            "option":["门","可","罗","雀"]
          },
          {
            "qtype":2,
            "img":"item/25.jpg",
            "option":["苦","口","婆","心"]
          },
          {
            "qtype":2,
            "img":"item/26.jpg",
            "option":["七","窍","生","烟"]
          },
          {
            "qtype":2,
            "img":"item/27.jpg",
            "option":["改","朝","换","代"]
          },
          {
            "qtype":2,
            "img":"item/28.jpg",
            "option":["百","步","穿","杨"]
          },
          {
            "qtype":2,
            "img":"item/29.jpg",
            "option":["地","广","人","稀"]
          },
          {
            "qtype":2,
            "img":"item/30.jpg",
            "option":["弥","天","大","谎"]
          },
          {
            "qtype":3,
            "img":"item/31.jpg",
            "right":"如虎添翼"
          },
          {
            "qtype":3,
            "img":"item/32.jpg",
            "right":"石破天惊"
          },
          {
            "qtype":3,
            "img":"item/33.jpg",
            "right":"人满为患"
          },
          {
            "qtype":3,
            "img":"item/34.jpg",
            "right":"背水一战"
          },
          {
            "qtype":3,
            "img":"item/35.jpg",
            "right":"闭门思过"
          },
          {
            "qtype":3,
            "img":"item/36.jpg",
            "right":"前仆后继"
          },
          {
            "qtype":3,
            "img":"item/37.jpg",
            "right":"束之高阁"
          },
          {
            "qtype":3,
            "img":"item/38.jpg",
            "right":"两厢情愿"
          },
          {
            "qtype":3,
            "img":"item/39.jpg",
            "right":"风卷残云"
          },
          {
            "qtype":3,
            "img":"item/40.jpg",
            "right":"归心似箭"
          }
      ],
  }
